import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../../models/project.dart';

class InvoiceService {
  static Future<void> generateAndShareInvoice(Project project) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Text('INVOICE', style: pw.TextStyle(fontSize: 32, fontWeight: pw.FontWeight.bold, color: PdfColors.deepPurple)),
              ),
              pw.SizedBox(height: 20),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Billed To:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 16)),
                      pw.Text(project.clientName),
                    ]
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('Invoice Date: ${DateTime.now().toString().split(' ')[0]}'),
                      pw.Text('Due Date: ${project.deadline?.toString().split(' ')[0] ?? 'N/A'}'),
                    ]
                  ),
                ]
              ),
              pw.SizedBox(height: 40),
              pw.Table.fromTextArray(
                context: context,
                border: pw.TableBorder.all(color: PdfColors.grey300),
                headerDecoration: const pw.BoxDecoration(color: PdfColors.deepPurple100),
                headerHeight: 40,
                cellHeight: 40,
                cellAlignments: {
                  0: pw.Alignment.centerLeft,
                  1: pw.Alignment.centerRight,
                },
                headers: ['Description', 'Amount'],
                data: [
                  [project.name, 'Rs. ${project.totalValue.toStringAsFixed(2)}'],
                  ['Total Due', 'Rs. ${project.totalValue.toStringAsFixed(2)}'],
                ],
              ),
              pw.Spacer(),
              pw.Divider(),
              pw.Text('Generated by FreelanceFlow', style: const pw.TextStyle(color: PdfColors.grey, fontSize: 12)),
            ],
          );
        },
      ),
    );

    await Printing.sharePdf(bytes: await pdf.save(), filename: 'invoice_${project.name.replaceAll(' ', '_')}.pdf');
  }
}
